channels:
  - defaults
  - conda-forge
  - anaconda
  - photosynthesis-team
  - pytorch
dependencies:
  - pytorch==1.8.0
  - torchvision==0.9.0
  - torchaudio==0.8.0
  - cudatoolkit=11.1
  - hydra
  - numpy
  - rich
  - lpips
  - piq
  - argparse
#  - pytorch-lightning
#  - rich
  - pillow
#  - matplotlib
  - imageio
  - tqdm
  - opencv